=== Solips1sm/uel112/Fichier_DTD.dtd
<!-- Anistratenco.S: (used acronym AS) from what it seems some people used xml versioning declaration in some YT guides on top, but the given examples do not mention it
so I will not bother overcomplicating-->
<!ELEMENT catalog (option_list, motor_types, cars)>

<!ELEMENT option_list (option+)> <!-- AS : I am really curious how the scope works with the element names...-->
<!ELEMENT motor_types (motor+)>  <!-- Can I use that name elsewhere..? huh..-->
<!ELEMENT cars (car*)>  <!-- nullable..? zero or more basically -->

<!ELEMENT option (#PCDATA)> <!--AS: It can be only PCDATA/CDATA..?-->
<!ATTLIST option
    option_ref ID #REQUIRED 
    value CDATA #REQUIRED>

<!ELEMENT motor (#PCDATA)>
<!ATTLIST motor
    motor_ref ID #REQUIRED>

<!ELEMENT car (subType, car_motor, color, manufacturer, year, reference, 
               price, options)>
<!ATTLIST car 
    id CDATA #REQUIRED>

<!ELEMENT subType (#PCDATA)>

<!ELEMENT car_motor EMPTY> <!-- changed name - I do not get how that makes any sense given a pre-existing motor. -->
<!ATTLIST car_motor
    motor_ref IDREF #REQUIRED>

<!ELEMENT color (#PCDATA)>
<!ATTLIST color
    hex CDATA #REQUIRED>
    
<!ELEMENT manufacturer (#PCDATA)>

<!ELEMENT year (#PCDATA)>

<!ELEMENT reference (#PCDATA)>
<!ATTLIST reference
    value CDATA #REQUIRED>

<!ELEMENT price (#PCDATA)>
<!ATTLIST price 
    value CDATA #REQUIRED>

<!ELEMENT options (config*)>

<!ELEMENT config EMPTY> <!--AS: contains only the atts -->
<!ATTLIST config 
    option_ref IDREF #REQUIRED>

=== Solips1sm/uel112/Fichier_XML.xml
<?xml version = "1.0" encoding="UTF-8"?> <!-- Anistratenco S. : The XML was validated on : "https://www.w3schools.com/xml/xml_validator.asp" -->
<!-- Anistratenco S. : updating the logic to refer to the common definitions of the options and motors as done in the original correction, as well as the cars.
        I would never personally store the entire catalogue as it is within a "singluar" xml and have all potential instances of motorTypes/options defined within it, because of recurrent R/W operations,
        and most likely a price mismatch on each ref. option/etc. -->
<!DOCTYPE base SYSTEM "Fichier_DTD.dtd">
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Fichier_XSD.xsd"> 

    <option_list>
        <option option_ref = "OCP" value="700">Personalized color</option>
        <option option_ref = "OEG" value="1000">Guaranteed extension</option>
        <option option_ref = "OVE" value="900">Electric window</option>
        <option option_ref = "OLC" value="200">CD reader</option>
    </option_list>

    <motor_types>
        <motor motor_ref = "ELEC">Electric</motor>
        <motor motor_ref = "THER">Thermal</motor>
        <motor motor_ref = "HYBR">Hybrid</motor>
    </motor_types>

    <cars> 

        <car id="0">
            <subType>Tourism</subType>
            <car_motor motor_ref ="ELEC"></car_motor>
            <color hex="#FF0000">red</color>
            <manufacturer>Peugeot</manufacturer>
            <year>2020</year>
            <reference value="985624">REF985624</reference>
            <price value="25000">25000 €</price> <!-- Anistratenco S. : had doubts about the euro sign being valid but found : "https://www.compart.com/en/unicode/U+20AC" -->
            <options>
                <config option_ref="OCP"></config>
                <config option_ref="OVE"></config>
                <config option_ref="OLC"></config>
            </options>
        </car>

        <car id="1">
            <subType>Utility</subType>
            <car_motor motor_ref ="THER"></car_motor>
            <color hex="#FFFFFF">white</color>
            <manufacturer>Ford</manufacturer>
            <year>2008</year>
            <reference value="125478">REF125478</reference>
            <price value="12000">12000 €</price>
            <options>
                <config option_ref="OCP"></config>
                <config option_ref="OVE"></config>
            </options>
        </car>

    </cars>

</catalog>
